### ISSUE TITLE
multiple migration directories support

### ISSUE THREAD

**Issue by GiTsu** [babenkoivan/elastic-migrations#36]
Hi. I develop my Laravel app using packages so they are located in different folders. Now it's impossible to load migrations from every package like standart laravel migrations can (only app-wise folder). [MigrationStorage](https://github.com/babenkoivan/elastic-migrations/blob/3e7f05043a699c4f4f48e70fb7a34f7d2d7e68a1/src/Filesystem/MigrationStorage.php) uses only one path from config. Is it possible somehow to add this path to an array by default and have some (facades?) method to call in package service provider for adding any custom folders to this array? Generates to one default folder, reads from multiple.

**Comment by babenkoivan** [comment]
Hey, it is somehow complicated due to the current package architecture. Maybe you can have some `post-install-cmd` composer script, which would copy migration files from all your directories to a single folder configured in `elastic.migrations.storage_directory`? This would be a much simpler solution.

**Comment by GiTsu** [comment]
Thanks, i'll try
